
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOT EQUALS FOR ID INT LBRACE LEQ LPAREN NUM PLUS RBRACE RPAREN SEMICOLON STRINGfor_loop : FOR INT ID EQUALS NUM SEMICOLON ID LEQ NUM SEMICOLON ID PLUS  '
    
_lr_action_items = {'FOR':([0,],[2,]),'$end':([1,13,],[0,-1,]),'INT':([2,],[3,]),'ID':([3,7,11,],[4,8,12,]),'EQUALS':([4,],[5,]),'NUM':([5,9,],[6,10,]),'SEMICOLON':([6,10,],[7,11,]),'LEQ':([8,],[9,]),'PLUS':([12,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'for_loop':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> for_loop","S'",1,None,None,None),
  ('for_loop -> FOR INT ID EQUALS NUM SEMICOLON ID LEQ NUM SEMICOLON ID PLUS','for_loop',12,'p_for_loop','AnalizadorSintatico.py',59),
]
