
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOT ELSE EQUALS FOR ID IF LBRACE LEQ LPAREN NOTEQ NUM PLUS RBRACE RPAREN SEMICOLON STRINGfor_loop : FOR ID ID  LPAREN NUM DOT DOT NUM RPAREN IF ID ID NUM EQUALS EQUALS NUM ID ID DOT ID PLUS STRING ELSE ID ID DOT ID PLUS STRING ID ID'
    
_lr_action_items = {'FOR':([0,],[2,]),'$end':([1,32,],[0,-1,]),'ID':([2,3,11,12,17,18,20,24,25,27,30,31,],[3,4,12,13,18,19,21,25,26,28,31,32,]),'LPAREN':([4,],[5,]),'NUM':([5,8,13,16,],[6,9,14,17,]),'DOT':([6,7,19,26,],[7,8,20,27,]),'RPAREN':([9,],[10,]),'IF':([10,],[11,]),'EQUALS':([14,15,],[15,16,]),'PLUS':([21,28,],[22,29,]),'STRING':([22,29,],[23,30,]),'ELSE':([23,],[24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'for_loop':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> for_loop","S'",1,None,None,None),
  ('for_loop -> FOR ID ID LPAREN NUM DOT DOT NUM RPAREN IF ID ID NUM EQUALS EQUALS NUM ID ID DOT ID PLUS STRING ELSE ID ID DOT ID PLUS STRING ID ID','for_loop',31,'p_for_loop','Analizador_Lexico_Sintatico.py',229),
]
